---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: bhag1988/api-gateway-service:v1.0
          ports:
            - containerPort: 8099

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  ports:
    - port: 8099
      targetPort: 8099
  selector:
    app: api-gateway-service
  type: LoadBalancer